### ISSUE TITLE
Choosing an option in jurisdiction or specialty 

### ISSUE THREAD

**Issue by BrandoCC** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#13]
When selecting a jurisdiction after a province is selected you have to click off of the screen to get the selection box to close. Similarly when choosing a specialty, after selecting the ones that are wanted you have to click outside the box. Is it possible to have a button on the bottom to click apply or the box closing automatically once the selections have been made?

**Comment by DaxBourcier** [comment]
Agreed, I think an apply button might be best rather than closing automatically because if you want to select more than one region and it keep closing that wouldn't be user friendly (for the comparing by jurisdictions one). I think closing automatically would be best when comparing by specialty because here there's only one jurisdiction to be picked.

**Comment by DaxBourcier** [comment]
Similarly to this issue, when you are on table view and want to compare specialties, when you select the jurisdiction, "All" is defaulted. To select a different health region, you need to unselect "All" before you can select another region. Ideally, the user would be able to simply click on another health region and the switch would occur automatically.
![Screen Shot 2020-04-25 at 9 07 56 PM](https://user-images.githubusercontent.com/62123024/80293810-34fb6e00-8739-11ea-8dce-7ef6bbf7f8ef.png)

**Comment by Jrschellenberg** [comment]
I am going to postpone this until after MVP. This would be a nice UI improvement!

**Comment by Jrschellenberg** [comment]
This is finished and will be Implemented in next release
