### ISSUE TITLE
When selecting Canada as a jurisdiction 

### ISSUE THREAD

**Issue by BrandoCC** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#14]
Redundant to have to select Canada again as a region.

**Comment by Jrschellenberg** [comment]
Please see the Screenshot Below. Canada is not needed to Be selected Again, as the logic will auto select Canada as a Region.

This is a fundamental requirement since the data needs to be split up as regions, and every Jurisdiction must have an "All" Region that encapsulates all of the Data of that region.

This is why this region appears here. Although I do see your point for not requiring it as it will be the only "Region" For the Jurisdiction of Canada. At this point in time, it is not worth the effort for hiding the Regions on a Unique Case by case basis, therefore. This may also prove to cause future bugs if regions are added to the Database, but are being hidden via the Front end View.

I will be closing this issue, for now, however, if you still disagree and wish to discuss this further please let me know and comment here!



<img width="1912" alt="Screen Shot 2020-03-14 at 3 32 35 PM" src="https://user-images.githubusercontent.com/6064137/76689975-ba9fe000-6609-11ea-9437-6af8289f438a.png">
