### ISSUE TITLE
HHRTF - Extra Data Sets

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#16]
Few things under data sets. 1) Some labels are "#" and other "Number", they should all be the latter. 2) There should be no abbreviations in the labels for example "Yr" should be "Year". CMG can be kept as an abbreviation.  3) PD_Response, Provincial Resources, Specialty resources should not appear under data sets. 4) # of graduate from province 2 yers ago should be changed to "Number Of Graduates" As per the update sent to CAPER on March 12th .

**Comment by Jrschellenberg** [comment]
In order to remedy this issue, we should correct the Template to have better naming for the Columns. Will investigate as to how hard this is to change with JT.

To clarify, the Columns need to be Exactly what you want rendered on the Front end, since that is what is being used to populate the name of the Data_set

**Comment by Jrschellenberg** [comment]
This is now Fixed with new CSV Upload
