### ISSUE TITLE
Graph view doesn't appear

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#51]
Graph view doesn't appear when applied. I've tried multiple data sets that I know we have and nothing appears. 

![image](https://user-images.githubusercontent.com/62123024/90830364-e8efbd00-e317-11ea-87bf-b03c6f4c4443.png)

**Comment by Jrschellenberg** [comment]
Hey Dax! I was investigating this. I have fixed the issue for comparing Specialities, However, it is still broken when comparing Jurisdictions.

I know what the cause of the bug is and will fix it, I was hoping to have this fixed for you before your meeting, but I ran out of time tonight. I should have the comparing Jurisdictions fixed next week though!

**Comment by DaxBourcier** [comment]
Sounds good, thanks

**Comment by Jrschellenberg** [comment]
Please investigate this again! It should be fixed now Dax! If you find another issue, just Reopen the ticket!
