### ISSUE TITLE
Update Zooming Functionality [UI]

### ISSUE THREAD

**Issue by Jrschellenberg** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#58]
Ideally when the user clicks on a province, it would zoom in to show the next level of data. Ex: Canadian region view, user clicks on any region it should show all of Canada, the user clicks on Québec, it should show the most zoomed out view that shows the health regions within Québec.

Investigate logic to handle zooming functionality,

**Comment by Jrschellenberg** [comment]
This is now fixed and will be available in next staged release

**Comment by DaxBourcier** [comment]
I also found out that the there is no interaction possible with the health regions when specialty demand layer is applied. Only some health regions are "clickable". Using the other layers there are no issues with this. I reopened the issue because I think it might be related.

![image](https://user-images.githubusercontent.com/62123024/91304477-ec53d000-e77f-11ea-9f07-464e02f6a58e.png)

**Comment by Jrschellenberg** [comment]
Make initial zoom -1

**Comment by Jrschellenberg** [comment]
Have the CaRMS data only get pulled in only when you query the following:

[
  {
    "name": "Number of CMG applicants"
  },
  {
    "name": "Number of CMG applicants who ranked specialty as first choice"
  }
]

It will only pull it in the CaRMS dataset, when the following above datasets are queried

**Comment by Jrschellenberg** [comment]
Related to Ticket #55

**Comment by Jrschellenberg** [comment]
This is now Fixed, Please Review @DaxBourcier and if there is no issues, you can close this ticket, if you still find issues, please let me know!

**Comment by DaxBourcier** [comment]
Great!!!
