### ISSUE TITLE
creating zooming ability for region information flags

### ISSUE THREAD

**Issue by basumoni** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#59]
In the map view, some regions (such as southern Ontario) look particularly crowded, and the pin with the information flag for each region is often placed outside of the central urban area for that region.

To help the user navigate all of this crowded information, we discussed it may be helpful if when a user clicks on a particular information flag, the view can zoom in to that flag so the user can easily see it.

**Comment by Jrschellenberg** [comment]
For Map View:

For Zooming functionality, do following:
When click map, do the current Map zooming logic, center screen and go in 1 more.

When user is at zoom level of 6+ Then do the following:
Old logic of fit the map to regional bounds.


Other Additions
Look into potentially adding a x in top right of Pop up Tooltip, that allows user to close the map marker, clicking map marker will reopen

When user Clicks the Pop up Tooltip, it will do the Map fit to bounds logic and zoom in the health region for the user.

**Comment by Jrschellenberg** [comment]
Implemented everything Above, still need to complete the following:

Other Additions
Look into potentially adding a x in top right of Pop up Tooltip, that allows user to close the map marker, clicking map marker will reopen

When user Clicks the Pop up Tooltip, it will do the Map fit to bounds logic and zoom in the health region for the user.

**Comment by Jrschellenberg** [comment]
@DaxBourcier This is ready for Review, Please note, I spent some time trying to implement the following:

`When the user Clicks the Pop-up Tooltip, it will do the Map fit to bounds logic and zoom in the health region for the user.`


However, It will be quite difficult to do, without doing a hacky workaround. I feel since the user can click the map layers to zoom in, I would like to postpone this for now. It may take a fair amount of restructuring of the data, as it is going against the way 
`react-leaflet` and `leaflet` libraries are currently implemented and will require a lot of additional custom work.

Let me know what you think. If it looks good, you can close the ticket, if you have any questions just let me know here!

**Comment by DaxBourcier** [comment]
I really like it with the "X" button! No problem for the clickable health region name. 

@basumoni  what are your thoughts on this?

**Comment by basumoni** [comment]
much nicer! Easy for the user to clean up with the x button
